public interface Info {

    /* (ASK TA IF THIS EXPLANATION IS ACCUARTE) SAY YOU HAVE TWO CLASSES THAT DON'T SHARE A COMMON SUPERCLASS AND YOU WANT THOSE TWO CLASSES TO USE THE SAME METHOD
    THEN YOU CAN USE AN INTERFACE TO ESSENTIALLY USE THE SAME METHOD in both classes. WHEN YOU USE THE METHOD IN THE INTERFACE CLASS, ARE YOU TECHNICALLY
    OVERRIDING it's METHOD(s) EACH TIME YOU GIVE EACH CLASS ITS IMPLEMENTATION FOR THAT METHOD?  */


    public void showInfo(); //NEVER GIVE THE METHODS IN THE INTERFACE IMPLEMENTAITON.
    public void identify();
    public static void hi() {
        System.out.println("hi");
    }

}
